import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navibar from "@/components/Navibar";
import QueryClientProvider from "@/components/QueryClientProvider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <QueryClientProvider>

        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-row`}
          >
            <div className="w-1/5 h-screen bg-gray-50">
              <Navibar />
            </div>
            <div className="w-4/5 h-screen">
              {children}
            </div>
          </body>
        </html>
      </QueryClientProvider>
    </ClerkProvider>
  );
}
